module.exports = [
  "A robot octopus DJing a party on a pirate ship.",
  "Three raccoons in a trench coat trying to buy a movie ticket.",
  "A city skyline made entirely of desserts.",
  "Knights jousting on unicycles.",
  "A library where the books fly like birds.",
  "A chameleon trying to blend in with a bag of Skittles.",
  "A dragon operating a lemonade stand.",
  "Penguins having a snowball fight in the Sahara desert.",
  "A sloth winning a marathon.",
  "A giant rubber duck causing a traffic jam.",
  "A house cat commanding a fleet of spaceships.",
  "A garden where the flowers are made of glass.",
  "A wizard trying to use a modern computer.",
  "A group of squirrels having a formal tea party.",
  "A whale swimming through the clouds.",
  "A snowman sunbathing on a tropical beach.",
  "A bear playing a grand piano in the middle of a forest.",
  "A submarine exploring a giant bowl of cereal.",
  "A giraffe wearing a dozen hats.",
  "A flock of sheep knitting sweaters for each other.",
  "A T-Rex trying to use a smartphone.",
  "A haunted house that's also a bouncy castle.",
  "A cactus giving free hugs.",
  "A group of goldfish driving a car.",
  "A mountain that is actually a sleeping giant.",
  "A tree that grows pasta instead of leaves.",
  "A group of frogs performing in a rock band.",
  "A cat and a dog playing a game of chess.",
  "A hamburger that is also a UFO.",
  "A group of penguins building an igloo on Mars.",
  "A clock melting over a tree branch in a desert.",
  "A staircase that leads to a door floating in the sky.",
  "A ship sailing on a sea of clouds.",
  "A forest where the trees are made of giant, colorful crystals.",
  "A key that unlocks a hidden world inside a book.",
  "A city street where the buildings are musical instruments.",
  "A child holding a balloon that contains a tiny galaxy.",
  "A bridge made of woven rainbows connecting two mountains.",
  "A teacup with a storm brewing inside it.",
  "A lone figure fishing for stars in a cosmic ocean.",
  "A mechanical heart with glowing gears and pipes.",
  "A path of stepping stones across a river of liquid light.",
  "An old-fashioned gramophone that plays the sounds of the forest.",
  "A giant, luminous jellyfish floating through a city at night.",
  "A door in the middle of a field that opens to a different season."
];
